---
title: "Лабораторная работа №4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(car)
library(censReg)
library(carData)
library(MASS)
library(caTools)
library(erer)
library(broom)
library(ggplot2)
library(memisc)
library(DescTools)
library(lmtest)
library(caTools)
library(dplyr)
library(readxl)
library(knitr)
library(kernlab)
library(caret)
library(mfx)
library(pROC)
library(ResourceSelection)
library(ROCR)
library(nortest)
library(MKmisc)
library(AER)
library(sampleSelection)
library(htmltools)
library(rmarkdown)
```
<h2>Цель: выяснить, что влияет на количество рабочих часов у женщин</h2>
<h3>Загрузим данные:</h3>
```{r}
data(Mroz87)
Mroz87<-Mroz87[which(Mroz87$wage<20),]
str(Mroz87)
```
<h3>Разделим выборку на тестовую и обучающую:</h3>
```{r}
set.seed(1827)
split <- sample.split(Mroz87$wage, SplitRatio = 0.70)
train <- subset(Mroz87, split == TRUE)
test <- subset(Mroz87, split == FALSE)
```

```{r}
model0<- tobit(wage ~ exper + I( exper^2 )+hours+kids5+educ+repwage+hushrs+huswage+mtr+nwifeinc,data = train)
summary(model0)
```


<h3>Построим модель цензурированной регрессии - Тобит</h3>
```{r}
model1<- tobit(wage ~ exper + I( exper^2 )+hours+kids5+educ+repwage+hushrs+huswage+mtr+nwifeinc, data = train)
summary(model1)
VIF(model1)
test$tobPred<-predict(model1, newdata = test)
ggplot(test, aes(x = wage, y = tobPred)) + geom_point() + geom_abline()
```
<h3>Построим модель цензурированной регрессии - Хекман</h3>
```{r, results='asis'}
Mroz87$kids  <- ( Mroz87$kids5 + Mroz87$kids618 > 0 )
# Двухэтапный метод
heck.m1 <- heckit( lfp ~ age + I( age^2 ) + faminc + kids + educ,
   wage ~ exper + I( exper^2 )+hours+kids5+educ+repwage+hushrs+huswage+mtr+nwifeinc, Mroz87, method = "2step" )
# ММП
heck.m2 <- heckit( lfp ~ age + I( age^2 ) + faminc + kids + educ,
   wage ~ exper + I( exper^2 )+hours+kids5+educ+repwage+hushrs+huswage+mtr+nwifeinc, Mroz87, method = "ml" )
# МНК
ols.m1 <- lm(wage ~ exper + I( exper^2 )+hours+kids5+educ+repwage+hushrs+huswage+mtr+nwifeinc, Mroz87)

stargazer::stargazer(ols.m1,heck.m1,heck.m2,type="html")
```

```{r}
test$heck1Pred<-predict(heck.m1, newdata = test)
ggplot(test, aes(x = wage, y = heck1Pred)) + geom_point() + geom_abline()
summary(heck.m1)
```

```{r}
test$heck2Pred<-predict(heck.m2, newdata = test)
ggplot(test, aes(x = wage, y = heck2Pred)) + geom_point() + geom_abline()
summary(heck.m2)
```

```{r}
test$olsPred<-predict(ols.m1, newdata = test)
ggplot(test, aes(x = wage, y = olsPred)) + geom_point() + geom_abline()
summary(ols.m1)
```

